accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
    login, logout,password_reset ,password_reset_done,password_reset_confirm,
    password_reset_complete
)

urlpatterns = [
                url(r'^$', views.home,name='home'),

                url(r'^login/$', views.login, { 'template_name':'accounts/login.html' },name='login' ),

                url(r'^logout/$', views.logout_view ,name='logout' ),

                url(r'^feedback/$', views.feedback ,name='feedback' ),

                url(r'^feedbacktillnow/$', views.feedbacktillnow, name='feedbacktillnow'),

                #url(r'^getsummary/$', views.getsummary, name='getsummary'),

                url(r'^register/$', views.register , name='register'),

                url(r'^register2/$',views.register2,name='register2'),

                url(r'^profile/$', views.view_profile , name='view_profile'),

                url(r'^profile/edit/$', views.edit_profile , name='edit_profile'),

                url(r'^change-password/$', views.change_password , name='change_password'),

                url(r'^reset-password/$', password_reset,
                        {'template_name': 'accounts/reset_password.html', 'post_reset_redirect': 'accounts:password_reset_done',
                         'email_template_name': 'accounts/reset_password_email.html'}, name='reset_password'),

                url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'},
                        name='password_reset_done'),

                url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
                        {'template_name': 'accounts/reset_password_confirm.html',
                         'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),

                url(r'^reset-password/complete/$', password_reset_complete,
                        {'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete'),

                url(r'^logout-feedback/$',login,{'template_name':'accounts/logoutfeed.html'},name='logoutfeed')
            ]

feed/urls.py
from django.conf.urls import url

from . import views

# from feed.views import FeedbackCreateView

app_name = 'feed'

urlpatterns = [
    # /feed/
    url(r'^$', views.index, name='index'),

    # /feed/34<project_id>
    url(r'^(?P<project_id>[0-9]+)/$', views.detail, name='detail'),

    # /feed/<project_id>/<module_id>
    url(r'^([0-9]+)/(?P<module_id>[0-9]+)/$', views.commit_detail, name='commit_detail'),

    url(r'^test/', views.test, name="test"),
    # # /feed/<project_id>/<module_id>/<commit_id>
    # url(r'^([0-9]+)/(?P<module_id>[0-9]+)/add/$', views.add_commit, name='add_commit'),
    url(r'^([0-9]+)/([0-9]+)/(?P<commit_id>[0-9]+)/$', views.comment_detail, name='comment_detail'),

    # url(r'^create/$', FeedbackCreateView.as_view(), name="feedback_create"),
]

logtest/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from logtest import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$',views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls',namespace='accounts')),
    url(r'^feed/', include('feed.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.
designation_choices = (
    (0, "Supervisor"),
    (1, "Project Manager"),
    (2, "Developer"),
    (3, "Client")
)
class UserProfile(models.Model):
    user = models.OneToOneField(User)
    designation = models.IntegerField(default = 3, choices = designation_choices)
    description = models.CharField(max_length=1000, default='')
    city = models.CharField(max_length=200,default='')
    website = models.URLField(null=True, blank=True, default='')
    phone = models.IntegerField(default=0)
    experience = models.IntegerField(default=0)
    skills = models.CharField(max_length=200, default='')
    emp_rating = models.FloatField(default=0)
    image = models.ImageField(upload_to='profile_image', blank=True)


    def __str__(self):
        return self.user.username

class Feedback(models.Model):
    feedback = models.CharField(max_length=1000, default='')
    #feedback_time = models.DateTimeField()

class Contact(models.Model):
    selectuser = models.CharField(max_length=1000,default='')



def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile,sender=User)


accounts/forms.py
import user

from django import forms
from django.contrib.auth.forms import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.forms import ModelForm

from accounts.models import UserProfile


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    username=forms.CharField(required=True,max_length=10)
    password1 = forms.CharField(required=True)
    password2 = forms.CharField(required=True)

    class Meta:
        model = User
        fields=(
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user=super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        if commit:
            user.save()

        return user

class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password',
        )

class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['description','city',
                  'website','phone','experience',
                  'skills','image']

        def save(self, commit=True):
            ob = super(UserProfileForm, self).save(commit=False)
            ob.description = self.cleaned_data['description']
            ob.city = self.cleaned_data['city']
            ob.website = self.cleaned_data['website']
            ob.phone = self.cleaned_data['phone']
            ob.experience = self.cleaned_data['experience']
            ob.skills = self.cleaned_data['skills']
            ob.image=self.cleaned_data['image']

            if commit:
                user.save()

            return ob

class FeedbackForm(forms.Form):
    feedback = forms.CharField(widget=forms.Textarea)

class ContactForm(forms.Form):
    selectuser = forms.CharField()

class ContactFilterForm(forms.Form):
    User = forms.ModelChoiceField(queryset=User.objects.all())

accounts/views.py
from django.http import HttpResponseRedirect,HttpResponse
from django.shortcuts import render,redirect
from accounts.forms import (
    RegistrationForm,
    EditProfileForm,
    UserProfileForm)
from accounts.models import UserProfile,Feedback,Contact
from accounts.forms import UserProfileForm,FeedbackForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm,PasswordChangeForm
import os
import datetime
from django.contrib.auth import logout
from django.shortcuts import render, redirect
from accounts.forms import (RegistrationForm,EditProfileForm,ContactFilterForm)
from accounts.forms import ContactForm
from django.conf import settings
from django.contrib.auth import (REDIRECT_FIELD_NAME, login as auth_login)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import (AuthenticationForm, PasswordChangeForm)
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponseRedirect
from django.shortcuts import resolve_url
from django.template.response import TemplateResponse
from django.utils.http import is_safe_url
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
# Create your views here.


def current_datetime(request):
    now = datetime.datetime.now()
    args={'time':now}
    return render(request, 'accounts/base.html', args)


@login_required
def home(request):
    args = {'user': request.user}
    return render(request , 'feed/index.html',args)

#feedback taking
@login_required
def feedback(request):
    if request.method == 'POST':
        feedback_form = FeedbackForm(request.POST)
        if feedback_form.is_valid():
            new_feedback = Feedback()
            new_feedback.feedback = feedback_form.cleaned_data['feedback']
            print(new_feedback.feedback)
            #new_feedback.feedback_time = timezone.now()
            #new_feedback.save()
            t = request.user
            logout_time = now = datetime.datetime.now()
            login_time = t.last_login
            filepath = os.path.join('datafolder', str(t))
            f = open(filepath, "a+")
            f.write("-----------------------------------------------------------------\n")
            f.write("Login Time: %s" % str(login_time.strftime("%Y-%m-%d %H:%M")) + "\n")
            f.write("Feedback: \n%s" % str(new_feedback.feedback) + "\n")
            f.write("Logout Time: %s" % str(logout_time.strftime("%Y-%m-%d %H:%M")) + "\n")

            f.write("-----------------------------------------------------------------\n\n")

            return HttpResponseRedirect('/account/logout')

    else:
        feedback_form = FeedbackForm()

    context = {'feedback_form': feedback_form,}
    return render(request, 'accounts/feedback_form.html', context)

#Feedback Retrieving
@login_required
def feedbacktillnow(request):
    if request.method == 'POST':
        contact_form = ContactFilterForm(request.POST)
        if contact_form.is_valid():

            t = contact_form.cleaned_data['User']
            print(t)
            #t = request.user
            directory = "datafolder/" + str(t)
            # print (ret_variable_count())

            filepath = os.path.join(directory)
            if os.path.exists(filepath):
                f = open(filepath, "r+")
                content = f.readlines()
                return HttpResponse(content, content_type='text/plain')
            else:
                print("summary not found")
                return HttpResponse("No Record Found")
    else:
        contact_form = ContactFilterForm()
        all_users = UserProfile.objects.all()

    context = {'contact_form': contact_form,}
    return render(request, 'accounts/summary.html', context)


def logout_view(request):
    print request.user
    logout(request)
    return HttpResponseRedirect('/account/login')

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/account/login/')

        else:
             return render(request, 'accounts/login1.html')
    else:
        form = RegistrationForm
        args = {'form': form, 'form_head': "Details"}
        return render(request, 'accounts/reg_form.html', args)

def register2(request):
    if request.method == 'POST':
        form = UserProfileForm(request.POST)
        if form.is_valid():
            hi = form.save(commit=False)
            hi.user = request.user
            UserProfile.objects.filter(user=request.user).delete()
            hi.save()
            return redirect('/account/profile')
    else:
        form = UserProfileForm()

        args = {'form': form,}
        return render(request,'accounts/reg_form_2.html',args)


@login_required
def view_profile(request):
    args = {'user': request.user}

    if request.method == 'POST':
        form1 = PasswordChangeForm(data=request.POST,user = request.user)

        if form1.is_valid():
            form1.save()
            return redirect('/account/profile')

    else:
        form1=PasswordChangeForm(user = request.user)
        args = {'form' : form1,
                'test': "Change Your Password"}
    return render(request, 'accounts/profile.html',args)

@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST,instance = request.user)

        if form.is_valid():
            form.save()
            return redirect('/account/profile')

    else:
        form=EditProfileForm(instance = request.user)
        args = {'form' : form}
        return render(request,'accounts/edit_profile.html',args)

@login_required
def change_password(request):
    if request.method == 'POST':
        form1 = PasswordChangeForm(data=request.POST,user = request.user)

        if form1.is_valid():
            form1.save()
            return redirect('/account/profile')

    else:
        form1=PasswordChangeForm(user = request.user)
        args = {'form' : form1,
                'test': "Change your Password"}
        return render(request,'accounts/profile.html',args)

@sensitive_post_parameters()
@csrf_protect
@never_cache
def login(request, template_name='registration/login.html',
          redirect_field_name=REDIRECT_FIELD_NAME,
          authentication_form=AuthenticationForm,
          current_app=None, extra_context=None):
    """
    Displays the login form and handles the login action.
    """
    redirect_to = request.POST.get(redirect_field_name,
                                   request.GET.get(redirect_field_name, ''))

    if request.method == "POST":
        form = authentication_form(request, data=request.POST)
        if form.is_valid():

            # Ensure the user-originating redirection url is safe.
            if not is_safe_url(url=redirect_to, host=request.get_host()):
                redirect_to = resolve_url(settings.LOGIN_REDIRECT_URL)

            # Okay, security check complete. Log the user in.
            auth_login(request, form.get_user())

            return HttpResponseRedirect(redirect_to)
        else:
            return render(request, 'accounts/login1.html')

    else:
        form = authentication_form(request)

    current_site = get_current_site(request)

    context = {
        'form': form,
        redirect_field_name: redirect_to,
        'site': current_site,
        'site_name': current_site.name,
    }
    if extra_context is not None:
        context.update(extra_context)

    if current_app is not None:
        request.current_app = current_app

    return TemplateResponse(request, template_name, context)



accounts/templates/accounts/home.html
{% extends 'base.html' %}
<h1 >home</h1>

    {% block head %}
    <title>home</title>
    {% endblock %}

    {% block body %}
        hey its me {{ user }}
        <br>

    {% endblock %}

accounts/templates/accounts/login1.html
{% extends 'base.html' %}

{% block head %}


    <title>Invalid Credentials</title>
 <link rel="stylesheet" media="all" href="https://hrcdn.net/hackerrank/assets/hackerrank-core-706c2914987d18c241bff6e251414ebb.css" />
    <link rel="stylesheet" media="all" href="https://hrcdn.net/hackerrank/assets/external_libraries-507bf28a74260fdc83d8547e5c699aa9.css" />
    <link rel="stylesheet" media="all" href="https://hrcdn.net/hackerrank/assets/auth-43c15f79360339f125f5aa081a6fc6d7.css" />
<link rel="stylesheet" id="js-hr-typography" type="text/css" href="https://hrcdn.net/lib/typography/345134/hosts/https/hrcdn.net/7C1B0FD393AD7F74A.css" data-noprefix />

    <link rel="stylesheet"
              href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">



{% endblock %}
{% block body %}
<br>
<br>
<br>

<div class="responsive-form block-center">
  <div class="login-group homepage_admin light-wrap">
        <center>
      <h4>User credentials entered are wrong</h4>

       <a href="{% url 'accounts:login' %}" class="btn btn-primary">Login  </a>
      <a href="{% url 'accounts:register' %}" class="btn btn-primary">Register</a>
</center>



      </div>
  </div>
  </div>

{% endblock %}




accounts/templates/accounts/logoutfeed.html
{% extends 'base.html' %}


    {% block head %}
    <title>Profile</title>
    {% endblock %}

    {% block body %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
                <p><label for="id_email">Email address:</label> <input type="email" name="email" value="11abhaystark@gmail.com" id="id_email" maxlength="254" /></p>
                <p><label for="id_first_name">First name:</label> <input type="text" name="first_name" value="Abhay Pratap" id="id_first_name" maxlength="30" /></p>
                <p><label for="id_last_name">Last name:</label> <input type="text" name="last_name" value="Singh" id="id_last_name" maxlength="30" /></p>

                <button type="submit">Submit</button>

        </form>
    </div>


    {% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}


{% block head %}
    <title>Profile</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


    <style>
    .cities {
    background-color: #ffffff;
    color: black;
    margin:5px 10px 5px 300px;;

    }
     .cities1 {
    background-color: #ffffff;
    color: black;
    margin:0px 0px 0px 0px;;

    }
    .card {
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
    transition: 0.3s;
    margin:80px 250px 50px 250px;
      }
      card:hover {
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
}
.card {
    position: relative;
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
    -webkit-flex-direction: column;
    -ms-flex-direction: column;
    flex-direction: column;
    background-color: #fff;
    border: 1px solid rgba(0, 0, 0, 0.125);
    border-radius: 0.25rem;
}

.card-block {
    -webkit-box-flex: 1;
    -webkit-flex: 1 1 auto;
    -ms-flex: 1 1 auto;
    flex: 1 1 auto;
    padding: 1.25rem;
}

.card-title {
    margin-bottom: 0.75rem;
}

.card-subtitle {
    margin-top: -0.375rem;
    margin-bottom: 0;
}

.card-text:last-child {
    margin-bottom: 0;
}

.card-link:hover {
    text-decoration: none;
}

.card-link + .card-link {
    margin-left: 1.25rem;
}

.card > .list-group:first-child .list-group-item:first-child {
    border-top-right-radius: 0.25rem;
    border-top-left-radius: 0.25rem;
}

.card > .list-group:last-child .list-group-item:last-child {
    border-bottom-right-radius: 0.25rem;
    border-bottom-left-radius: 0.25rem;
}

.card-header {
    padding: 0.75rem 1.25rem;
    margin-bottom: 0;
    background-color: #2f4f4f;
    color:#00afff;
    border-bottom: 1px solid rgba(0, 0, 0, 0.125);
}

.card-header:first-child {
    border-radius: calc(0.25rem - 1px) calc(0.25rem - 1px) 0 0;
}

.card-footer {
    padding: 0.75rem 1.25rem;
    background-color: #f7f7f9;
    border-top: 1px solid rgba(0, 0, 0, 0.125);
}

.card-footer:last-child {
    border-radius: 0 0 calc(0.25rem - 1px) calc(0.25rem - 1px);
}

.card-header-tabs {
    margin-right: -0.625rem;
    margin-bottom: -0.75rem;
    margin-left: -0.625rem;
    border-bottom: 0;
}

.card-header-pills {
    margin-right: -0.625rem;
    margin-left: -0.625rem;
}

.card-primary {
    background-color: #0275d8;
    border-color: #0275d8;
}

.card-primary .card-header,
.card-primary .card-footer {
    background-color: transparent;
}

.card-success {
    background-color: #5cb85c;
    border-color: #5cb85c;
}

.card-success .card-header,
.card-success .card-footer {
    background-color: transparent;
}

.card-info {
    background-color: #5bc0de;
    border-color: #5bc0de;
}

.card-info .card-header,
.card-info .card-footer {
    background-color: transparent;
}

.card-warning {
    background-color: #f0ad4e;
    border-color: #f0ad4e;
}

.card-warning .card-header,
.card-warning .card-footer {
    background-color: transparent;
}

.card-danger {
    background-color: #d9534f;
    border-color: #d9534f;
}

.card-danger .card-header,
.card-danger .card-footer {
    background-color: transparent;
}

.card-outline-primary {
    background-color: transparent;
    border-color: #0275d8;
}

.card-outline-secondary {
    background-color: transparent;
    border-color: #ccc;
}

.card-outline-info {
    background-color: transparent;
    border-color: #5bc0de;
}

.card-outline-success {
    background-color: transparent;
    border-color: #5cb85c;
}

.card-outline-warning {
    background-color: transparent;
    border-color: #f0ad4e;
}

.card-outline-danger {
    background-color: transparent;
    border-color: #d9534f;
}

.card-inverse {
    color: rgba(255, 255, 255, 0.65);
}

.card-inverse .card-header,
.card-inverse .card-footer {
    background-color: transparent;
    border-color: rgba(255, 255, 255, 0.2);
}

.card-inverse .card-header,
.card-inverse .card-footer,
.card-inverse .card-title,
.card-inverse .card-blockquote {
    color: #fff;
}

.card-inverse .card-link,
.card-inverse .card-text,
.card-inverse .card-subtitle,
.card-inverse .card-blockquote .blockquote-footer {
    color: rgba(255, 255, 255, 0.65);
}

.card-inverse .card-link:focus, .card-inverse .card-link:hover {
    color: #fff;
}

.card-blockquote {
    padding: 0;
    margin-bottom: 0;
    border-left: 0;
}

.card-img {
    border-radius: calc(0.25rem - 1px);
}

.card-img-overlay {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    padding: 1.25rem;
}

.card-img-top {
    border-top-right-radius: calc(0.25rem - 1px);
    border-top-left-radius: calc(0.25rem - 1px);
}

.card-img-bottom {
    border-bottom-right-radius: calc(0.25rem - 1px);
    border-bottom-left-radius: calc(0.25rem - 1px);
}

@media (min-width: 576px) {
    .card-deck {
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
        -webkit-flex-flow: row wrap;
        -ms-flex-flow: row wrap;
        flex-flow: row wrap;
    }
    .card-deck .card {
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-flex: 1;
        -webkit-flex: 1 0 0%;
        -ms-flex: 1 0 0%;
        flex: 1 0 0%;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -webkit-flex-direction: column;
        -ms-flex-direction: column;
        flex-direction: column;
    }
    .card-deck .card:not(:first-child) {
        margin-left: 15px;
    }
    .card-deck .card:not(:last-child) {
        margin-right: 15px;
    }
}

@media (min-width: 576px) {
    .card-group {
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
        -webkit-flex-flow: row wrap;
        -ms-flex-flow: row wrap;
        flex-flow: row wrap;
    }
    .card-group .card {
        -webkit-box-flex: 1;
        -webkit-flex: 1 0 0%;
        -ms-flex: 1 0 0%;
        flex: 1 0 0%;
    }
    .card-group .card + .card {
        margin-left: 0;
        border-left: 0;
    }
    .card-group .card:first-child {
        border-bottom-right-radius: 0;
        border-top-right-radius: 0;
    }
    .card-group .card:first-child .card-img-top {
        border-top-right-radius: 0;
    }
    .card-group .card:first-child .card-img-bottom {
        border-bottom-right-radius: 0;
    }
    .card-group .card:last-child {
        border-bottom-left-radius: 0;
        border-top-left-radius: 0;
    }
    .card-group .card:last-child .card-img-top {
        border-top-left-radius: 0;
    }
    .card-group .card:last-child .card-img-bottom {
        border-bottom-left-radius: 0;
    }
    .card-group .card:not(:first-child):not(:last-child) {
        border-radius: 0;
    }
    .card-group .card:not(:first-child):not(:last-child) .card-img-top,
    .card-group .card:not(:first-child):not(:last-child) .card-img-bottom {
        border-radius: 0;
    }
}

@media (min-width: 576px) {
    .card-columns {
        -webkit-column-count: 3;
        -moz-column-count: 3;
        column-count: 3;
        -webkit-column-gap: 1.25rem;
        -moz-column-gap: 1.25rem;
        column-gap: 1.25rem;
    }
    .card-columns .card {
        display: inline-block;
        width: 100%;
        margin-bottom: 0.75rem;
    }
}

body {margin:25px;}

div.polaroid {
  width: 80%;
  background-color: white;
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
  margin-bottom: 25px;
}

div.container {
  text-align: center;
  padding: 10px 20px;
}
    </style>
{% endblock %}

{% block body %}
<body style="background-color: #f5f5f5">
<div class="card">
    <div class="card-header">
        <h4 class="card-title">Personal Details</h4>
    </div>
    <div class="card-block">
        <div class="row">
            <div class="col-sm-4" >
                <center>
                    <br>
                        <br>
                    <div class="card-img-overlay">

                        <img src="{{ user.userprofile.image.url }}" class="img-rounded" alt="Cinque Terre" width="60%">
                        <p>{%if user.userprofile.designation == 0 %}
                        <h4>Supervisor</h4>
                            {%elif user.userprofile.designation == 1 %}
                        <h4>Project Manager</h4>
                            {%elif user.userprofile.designation == 2 %}
                        <h4>Developer</h4>
                            {%elif user.userprofile.designation == 3 %}
                        <h4> Client</h4>
                            {%endif%}
                        </p>
                    </div>
                </center>
            </div>
            <div class="col-sm-8">
                <br>
                <p class="card-text"><b>Username&nbsp&nbsp&nbsp&nbsp:</b>       {{ user }}</p>
                <p class="card-text"><b>First name&nbsp&nbsp&nbsp:</b>     {{ user.first_name }} {{ user.last_name }}</p>
                <p class="card-text"><b>Email &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp: </b>{{ user.email }}</p>
                <p class="card-text"><b>Phone &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp:</b>{{user.userprofile.phone}}</p>
                <p class="card-text"><b>Address &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp:</b>{{user.userprofile.city}}</p>
                <p class="card-text"><b>Skills &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp:</b>{{user.userprofile.skills}}</p>
                <p class="card-text"><b>Website &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp:</b><a href="{{user.userprofile.website}}">{{user.userprofile.website}}</a></p>
                <p class="card-text"><b>Description&nbsp :</b>{{user.userprofile.description}}</p>
                <p class="card-text"><b>Emp Rating&nbsp&nbsp: </b>{{user.userprofile.emp_rating}}</p>
                <a href="{% url 'accounts:register2' %}" class="btn btn-primary">Add Details</a>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Change Password</button>
                    {% include 'accounts/change_password.html' %}


            </div>
        </div>
    </div>
</div>
<div class="card " class="cities">
<div class="card-header">
                 <h4 class="card-title">Project Details</h4>
        </div>
        <div class="card-block">
 
<br>
		  <b>Project 1</b>
			This is a description for Project 1.
<br><br>
			<b>Project 2</b>
			This is a description for Project 2.

            <br>
        </div>

</div>
</body>
{% endblock %}