feed/urls.py
from django.conf.urls import url

from . import views

# from feed.views import FeedbackCreateView

app_name = 'feed'

urlpatterns = [
    # /feed/
    url(r'^$', views.index, name='index'),

    # /feed/34<project_id>
    url(r'^(?P<project_id>[0-9]+)/$', views.detail, name='detail'),

    # /feed/<project_id>/<module_id>
    url(r'^([0-9]+)/(?P<module_id>[0-9]+)/$', views.commit_detail, name='commit_detail'),

    url(r'^test/', views.test, name="test"),
    # # /feed/<project_id>/<module_id>/<commit_id>
    # url(r'^([0-9]+)/(?P<module_id>[0-9]+)/add/$', views.add_commit, name='add_commit'),
    url(r'^([0-9]+)/([0-9]+)/(?P<commit_id>[0-9]+)/$', views.comment_detail, name='comment_detail'),

    # url(r'^create/$', FeedbackCreateView.as_view(), name="feedback_create"),
]

logtest/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from logtest import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$',views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls',namespace='accounts')),
    url(r'^feed/', include('feed.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


# Create your models here.

# Project Table -- contains info for a particular project.

class Project(models.Model):
    name = models.CharField(max_length=250, default="project0")
    manager_id = models.IntegerField(default=0)
    description = models.CharField(max_length=1000)
    publish = models.DateField()
    terminate = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.name + ' - ' + self.description


# Module Table -- Contains info of all the modules from all the projects, and can be grouped into
# a particular project using the project id

class Module(models.Model):
    project_id = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=500, default="module0")
    description = models.CharField(max_length=1000)
    publish = models.DateTimeField()
    terminate = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.name + ' - ' + self.description


# Commit Table -- Contains all the information of all the commits till date for all the modules of
# all the projects. They can be grouped together using the module_id

class Commit(models.Model):
    module_id = models.ForeignKey(Module, on_delete=models.CASCADE)
    user_id = models.IntegerField()
    name = models.CharField(max_length=500, default="commit0")
    description = models.CharField(max_length=1000)
    publish = models.DateTimeField()
    file = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.name + ' - ' + self.description


# Comments Table -- Contains all the comments till date. They can be grouped together using the
# commit_id. Whenever a client reads a commit he may post a comment and that comment can then
# be retrieved using the commit_id

class Comment(models.Model):
    commit_id = models.ForeignKey(Commit, on_delete=models.CASCADE)
    user_id = models.IntegerField()
    description = models.CharField(max_length=1000)
    publish = models.DateTimeField()
    file = models.FileField(null=True, blank=True)

    def __str__(self):
        return 'User: ' + str(self.user_id) + ' - ' + str(self.commit_id) + ' - ' + str(self.description)


# Log Table -- It will contain the log entry of every individual working in the organisation.
# Whenever the user asks to logout he will be prompted to enter the summary of the work he has done
# on that day.

class Log(models.Model):
    user_id = models.IntegerField(default=0)
    clock_in = models.DateTimeField()
    clock_out = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.user_id + ' Total: ' + (self.clock_out - self.clock_in)


class Summary(models.Model):
    user_id = models.IntegerField()
    description = models.CharField(max_length=1000)
    publish = models.DateTimeField()

    def __str__(self):
        return self.user_id + ' - ' + self.description

feed/forms.py
from django import forms


class ProjectForm(forms.Form):
    name = forms.CharField(label='Name', max_length=250)
    manager_id = forms.CharField(label='Manager Id', max_length=10)
    description = forms.CharField(widget=forms.Textarea)


class ModuleForm(forms.Form):
    name = forms.CharField(label='Name', max_length=250)
    description = forms.CharField(widget=forms.Textarea)


class CommitForm(forms.Form):
    name = forms.CharField(label='Name', max_length=250)
    description = forms.CharField(widget=forms.Textarea)
    user_id = forms.IntegerField(label='User Id')
    file = forms.FileField(label='Upload File')


class CommentForm(forms.Form):
    name = forms.CharField(label='Name', max_length=250)
    user_id = forms.IntegerField(label='User Id')
    description = forms.CharField(widget=forms.Textarea)
    file = forms.FileField(label='Upload File')

feed/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.utils import timezone

from .forms import ProjectForm, ModuleForm, CommitForm
from .models import Project, Module, Commit, Comment

app_name = 'feed'


def index(request):
    all_projects = Project.objects.all()
    if request.method == 'POST':
        project_form = ProjectForm(request.POST, prefix="project")
        if project_form.is_valid():
            new_project = Project()
            new_project.name = project_form.cleaned_data['name']
            new_project.manager_id = project_form.cleaned_data['manager_id']
            new_project.description = project_form.cleaned_data['description']
            new_project.publish = timezone.now()
            new_project.save()
            return HttpResponseRedirect('/feed')

    else:
        project_form = ProjectForm(prefix='project')

    context = {'all_projects': all_projects,
               'project_form': project_form,
               'form_head': "Project",
               }
    return render(request, 'feed/index.html', context)


def detail(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if request.method == 'POST':
        module_form = ModuleForm(request.POST, prefix="module")
        if module_form.is_valid():
            try:
                new_module = Module()
                new_module.project_id = Project.objects.filter(id=project_id)[0]
                new_module.name = module_form.cleaned_data['name']
                new_module.description = module_form.cleaned_data['description']
                new_module.publish = timezone.now()
                new_module.save()
            except Exception as e:
                print(e)
            else:
                # print("New Module added", new_module.name, new_module.description)
                return HttpResponseRedirect('/feed')

    else:
        module_form = ModuleForm(prefix="module")

    return render(request, 'feed/detail.html', {'module_form': module_form,
                                                'form_head': "Module",
                                                'project':project,
                                              })


def commit_detail(request, module_id):
    mod = get_object_or_404(Module, pk=module_id)
    p = Project.objects.filter(module=mod)
    project_id = p[0].id
    all_commits = Commit.objects.filter(module_id=module_id)
    if request.method == 'POST':
        commit_form = CommitForm(request.POST, request.FILES, prefix="commit")
        if commit_form.is_valid():
            new_commit = Commit()
            new_commit.module_id = Module.objects.filter(id=module_id)[0]
            new_commit.name = commit_form.cleaned_data['name']
            new_commit.user_id = commit_form.cleaned_data['user_id']
            new_commit.description = commit_form.cleaned_data['description']
            new_commit.file = request.FILES['commit-file']
            new_commit.publish = timezone.now()
            new_commit.save()
            return HttpResponseRedirect('/feed')

    else:
        commit_form = CommitForm(prefix="commit")
    context = {
        'all_commits': all_commits,
        'module': mod,
        'project_id': project_id,
        'commit_form':commit_form,
    }
    return render(request, 'feed/commit_detail.html', context)


def comment_detail(request, commit_id):
    commit = get_object_or_404(Commit, id=commit_id)
    all_comments = Comment.objects.filter(commit_id=commit)
    context = {
        'all_comments': all_comments,
    }
    return render(request, 'feed/comment_detail.html', context)


def test(request):
    return render(request, 'feed/test.html')

feed/templates/feed/comment_detail.html
{% include 'feed/header.html' %}
<body>
{% if all_comments %}
    {% for comment in all_comments %}
        <div class="card-panel blue-grey lighten-4 text-darken-2">
            <p><span class="blue-text">{{comment.user_id}}: &nbsp;</span>{{comment.description}}<span class="pull-right">{{comment.publish}}</span></p>
            {% if comment.file %}
                <span> <a  href="{{comment.file}}">File</a></span>
            {% endif %}
        </div>
    {% endfor %}
{% endif %}
</body>

feed/templates/feed/commit_detail.html
{% include "feed/header.html" %}
<h4>Module: {{module.name}}<button type="button" class="btn btn-info btn-lg pull-right" data-toggle="modal" data-target="#CommitModal">Add Commit</button></h4>
<h5>{{module.description}}</h5>
<script>
    function update_comments(project_id, module_id, commit_id){
        document.getElementById('btn_see_comments_' + commit_id).style.display = 'none';
        $.ajax({
            url : '/feed/' + project_id + '/' + module_id + '/' + commit_id,
            success : function(data){
                $('#comments_section'+commit_id).html(data);
            }
        });
    }
</script>
{% if module.commit_set.all %}
    {% for commit in module.commit_set.all %}
        {% include 'feed/cards/card_commit.html' with commit=commit %}
    {% endfor %}
{% else %}
    <h5>No commits yet.</h5>
{% endif %}


<div class="container">
    <!-- Modal -->
    <div class="modal fade" id="CommitModal" role="dialog">
        <!--<div class="modal-dialog">-->
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Add Commit</h4>
                </div>
                <div class="modal-body">
                    <form action="{% url 'feed:commit_detail' project_id module.id  %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <table>
                            {{ commit_form.as_table }}
                        </table>
                        <button class="btn waves-effect waves-light" type="submit" name="action">Submit<i class="material-icons right">send</i></button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </form>
                </div>
            </div>
        <!--</div>-->
    </div>
</div>

feed/templates/feed/detail.html
{% include 'feed/header.html' %}
<script>
    function update_commits_section( project_id, module_id){
         $.ajax({
            url : '/feed/' + project_id + '/' + module_id,
            success : function(data){
                $('#commits_section').html(data);
            }
        });
    }
</script>
<!--<script>-->
    <!--function myFunction(){-->
        <!--alert({{ test_word }});-->
    <!--}-->
<!--</script>-->
<h4>Modules &nbsp <button type="button" class="btn btn-info btn-lg pull-right" data-toggle="modal" data-target="#ModuleModal">Add</button></h4>
<h5>Project:  {{ project.name }}</h5>
<div style="height: 30vh;overflow-x: hidden; overflow-y: scroll;">



    {% if project.module_set.all %}
        {% for module in project.module_set.all %}
            {% include 'feed/cards/card_module.html' with module=module %}
        {% endfor %}
    {% else %}
        <h5>No Modules found. Please add some modules to this Project</h5>
    {% endif %}





    <div class="container">
        <!--<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#ModuleModal">Add {{form_head}}</button>-->
        <!-- Modal -->
        <div class="modal fade" id="ModuleModal" role="dialog">
            <!--<div class="modal-dialog">-->
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Add {{form_head}}</h4>
                    </div>
                    <div class="modal-body">
                        <form action="{% url 'feed:detail' project.id  %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <table>
                                {{ module_form.as_table }}
                            </table>
                            <button class="btn waves-effect waves-light" type="submit" name="action">Submit<i class="material-icons right">send</i></button>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </form>
                    </div>
                </div>
            <!--</div>-->
        </div>
    </div>
    <!--<button onclick="myFunction()">Click Me!</button>-->

</div>

feed/templates/feed/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.1/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/css?family=Patrick+Hand+SC|Rock+Salt&amp;subset=latin-ext" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
    <title>Intranet</title>
</head>

feed/templates/feed/index.html
{% extends 'base.html' %}
{% block head %}
{% include 'feed/header.html' %}
{% endblock %}
{% block body %}

<body onload="update_module_section(1)">
<div class="navbar-fixed">
    <!--<nav>
        <div class="nav-wrapper">
            <a href="#" class="brand-logo" style="font-family:'Rock Salt'">&nbsp;Intranet</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="#" style="font-family:'Patrick Hand SC'; font-size:20px">Home</a></li>
                <li><a href="#" style="font-family:'Patrick Hand SC'; font-size:20px">Profile</a></li>
            </ul>
        </div>
    </nav>-->
</div>
<div class="container-fluid" style="height: auto; width: auto">
    <script>
    function update_module_section(project_id){
        $.ajax({
            url: '/feed/'+project_id,
            success : function(data){
                $('#module_section').html(data);
            }
        });
    }
    </script>
    <script type="text/javascript">
    </script>
    <div class="full">
        <div class="row">
            <div class="col-sm-3 " id = "project_section" style="height:92vh;">
                <h4>Projects &nbsp <button type="button" class="btn btn-info btn-lg pull-right" data-toggle="modal" data-target="#ProjectModal">Add</button></h4>
                <div style="height: 33vh; overflow-x: hidden; overflow-y: scroll;">
                    {% if all_projects %}
                        {% for project in all_projects %}
                            {% include "feed/cards/card_project.html" with project=project  only  %}
                        {% endfor %}
                    {% else %}
                    <h6>Please add some projects to display</h6>
                    {% endif %}
                </div>

                <!-- Modal -->
                <div class="modal fade" id="ProjectModal" role="dialog">
                    <!--<div class="modal-dialog">-->
                        <!-- Modal content-->
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title">Add {{form_head}}</h4>
                            </div>
                            <div class="modal-body">
                                <form action="" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <table>
                                        {{ project_form.as_table }}
                                    </table>
                                    <button class="btn waves-effect waves-light" type="submit" name="action">Submit<i class="material-icons right"></i></button>
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                </form>

                            </div>
                        </div>
                    <!--</div>-->
                </div>
                <!-- Modal End -->

                <div style="height: auto;" id = "module_section" ></div>
                <div>

                </div>
            </div>
            <div class="col-sm-7" id="commits_section" style="background-color:#ffffff;height:92vh; overflow-x: hidden; overflow-y: scroll;"></div>
            <div class="col-sm-2" style="background-color:#ff6666;height:92vh; overflow-x: hidden; overflow-y: scroll;">Chat Area</div>
        </div>
    </div>
</div>
{% endblock %}

feed/templates/feed/test.html
{% include "feed/header.html" %}
<a class="waves-effect waves-light btn modal-trigger" onclick="openModal()" href="#modal1">Modal</a>

  <!-- Modal Structure -->
  <div id="modal1" class="modal">
    <div class="modal-content">
      <h4>Modal Header</h4>
      <p>A bunch of text</p>
    </div>
    <div class="modal-footer">
      <a href="" onclick="closeModal()" class="modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
    </div>
  </div>

<script>
   function openModal(){
      $('.modal').modal();
   }
   function closeModal(){
       $('#modal1').modal('close');
   }
</script>



<!--   <ul>
                        {% for project in all_projects %}
                            <li>{{project.name}}</li>
                            <button onclick="update_module_section({{project.id}})">Show Details</button>
                        {% endfor %}
                    </ul>
                    {% else %}
                    <h6>Please add some projects to display</h6>
                    {% endif %}
                </div>-->



<!--card_commit.html-->
 <!-- <div class="w3-container"style="margin-bottom: 20px;margin-left: -10px;">
        <div class="w3-card-4">
            <header class="w3-container w3-green">
            <h4>{{commit.name}}</h4>
            <h5 class="pull-right">User ID: {{commit.user_id}}</h5>
            </header>

            <div class="w3-container"style="padding: 10px;">
                <p>{{commit.description}}</p>
                &lt;!&ndash;<p>Here:{{project_id}},{{module.id}},{{forloop.counter}}</p>&ndash;&gt;
                <div class="container" id = "comments_section{{forloop.counter}}">Division it is</div>
                <button onclick="update_comments({{project_id}},{{module.id}},{{commit.id}})">Show Comments</button>
            </div>

            <footer class="w3-container w3-gray">
            <strong>{{commit.publish}}</strong>
            </footer>
        </div>
    </div>-->